[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
rust-version = "1.71"
edition = "2021"
license = "GPL-3.0"
authors = ["Chris Morrison"]
repository = "https://github.com/CMorrison82z/tiled_import"
readme = "README.md"

[workspace.dependencies]
tiled_parse = { path = "crates/tiled_parse", version = "0.2.2" }
tiled_parse_tree = { path = "crates/tree", version = "0.1.1" }
bevy_tiled_loader = { path = "crates/bevy_tiled_loader", version = "0.2.2" }

try_match = "0.4.2"
criterion = "0.6"
futures = "0.3.31"
itertools = "^0.14.0"
ndarray = "0.15.6"
