[package]
name = "tiled_parse"
version = "0.2.3"
description = "Tiled tmx parser with nom."
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ["tiled", "tmx", "parse"]
categories = ["development-tools", "game-development"]

[dependencies]
ndarray.workspace = true
try_match.workspace = true
itertools.workspace = true
tiled_parse_tree.workspace = true
# TODO: Put behind a feature flag 'external_tile_set'
futures-util = {version = "0.3", default-features = false, features = ["alloc"]}
nom = "7.1.3"
base64 = "^0.22.1"
xml_nom_parse = "0.3"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "big_tmx_bench"
harness = false
