[package]
name = "tiled_parse_tree"
version = "0.1.0"
description = "An implementation of a Tree data structure."
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ["tree", "data structure"]
categories = ["data structures"]
