[package]
name = "bevy_tiled_loader"
version = "0.1.1"
description = "Asset loader for the Tiled data parsed."
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ["tiled", "tmx", "parse", "bevy"]
categories = ["development-tools", "game-development"]

[features]
default = []
rapier2d_colliders = ["dep:bevy_rapier2d"]
avian2d_colliders = ["dep:avian2d"]

[dependencies]
try_match.workspace = true
tiled_parse.workspace = true
bevy_platform = "0.16.0"
bevy = {version = "0.16.0", features = [
  "bevy_asset",
  "bevy_sprite",
  "png",
]}
serde = "1.0.210"
bincode = "1.3.3"
bevy_rapier2d = { version = "0.28.0", features = ["serde-serialize"], optional = true }
avian2d = { version = "0.2.0", features = ["serialize"], optional = true }


[dev-dependencies]
bevy = { version = "0.16.0", default-features = true }
avian2d = "0.2.0"
bevy_rapier2d = "0.28.0"

[[example]]
name = "load_tiled_components"
required-features = ["avian2d_colliders"]
